# Generated by Django 4.2.7 on 2024-02-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='restaurant_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='food_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='small_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
